services:
  postgres:
    container_name: airflow-postgres
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5
    restart: unless-stopped

  postgres-superset:
    container_name: superset-postgres
    image: postgres:13
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - "5433:5432"
    volumes:
      - postgres_superset_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superset"]
      interval: 5s
      retries: 5
    restart: unless-stopped

  airflow-webserver:
    container_name: airflow-webserver
    image: apache/airflow:2.6.3
    user: "${AIRFLOW_UID:-0}:0"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin && airflow webserver"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  airflow-scheduler:
    container_name: airflow-scheduler
    image: apache/airflow:2.6.3
    user: "${AIRFLOW_UID:-0}:0"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__SCHEDULER__MAX_CATCHUP_RUNS=2000
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - airflow-webserver
      - postgres
    command: scheduler
    restart: unless-stopped

  superset:
    container_name: superset
    image: apache/superset:latest
    environment:
      SUPERSET_SECRET_KEY: 'lbjBNHfzy8LzzCGkygsJGFZK6lM+wFEscyN3vnXoftDIzeHVXvNZbWaN'
      SUPERSET_DATABASE_URI: 'postgresql+psycopg2://superset:superset@superset-postgres/superset'
    ports:
      - "8088:8088"
    depends_on:
      - postgres-superset
    volumes:
      - superset_data:/app/superset_home
    command: >
      bash -c "
        pip install psycopg2-binary &&
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin || true &&
        superset init &&
        /usr/bin/run-server.sh
      "
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"     # API и доступ к данным
      - "9001:9001"     # Веб-интерфейс и администрирование
    volumes:
      - ~/data/minio:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123456
    command: server /data --console-address :9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_superset_data:
  superset_data: